[tool.poetry]
name = "okuninushi"
version = "0.1.0"
description = ""
authors = ["Joao Pedro Jacques Hoss <joaopedro_jh@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
